/* Generated By:JavaCC: Do not edit this line. ExampleConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExampleConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPP = 1;
  /** RegularExpression Id. */
  int OPS = 2;
  /** RegularExpression Id. */
  int NUMBER = 3;
  /** RegularExpression Id. */
  int REALNUMBER = 4;
  /** RegularExpression Id. */
  int EQUAL = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<OPP>",
    "<OPS>",
    "<NUMBER>",
    "<REALNUMBER>",
    "\"=\"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\" \"",
  };

}
