/* Generated By:JavaCC: Do not edit this line. ExampleConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExampleConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int create = 1;
  /** RegularExpression Id. */
  int element = 2;
  /** RegularExpression Id. */
  int img = 3;
  /** RegularExpression Id. */
  int header = 4;
  /** RegularExpression Id. */
  int para = 5;
  /** RegularExpression Id. */
  int url = 6;
  /** RegularExpression Id. */
  int decorated_text = 7;
  /** RegularExpression Id. */
  int decorated_url = 8;
  /** RegularExpression Id. */
  int text = 9;
  /** RegularExpression Id. */
  int color = 10;
  /** RegularExpression Id. */
  int font = 11;
  /** RegularExpression Id. */
  int link = 12;
  /** RegularExpression Id. */
  int quote = 13;
  /** RegularExpression Id. */
  int alphanumeric = 14;
  /** RegularExpression Id. */
  int sentence = 15;
  /** RegularExpression Id. */
  int string = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<create>",
    "<element>",
    "<img>",
    "<header>",
    "<para>",
    "<url>",
    "<decorated_text>",
    "<decorated_url>",
    "<text>",
    "<color>",
    "<font>",
    "<link>",
    "\"\\\"\"",
    "<alphanumeric>",
    "<sentence>",
    "<string>",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
  };

}
