/* Generated By:JavaCC: Do not edit this line. ExampleConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExampleConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPP = 1;
  /** RegularExpression Id. */
  int OPS = 2;
  /** RegularExpression Id. */
  int NUMBER = 3;
  /** RegularExpression Id. */
  int REALNUMBER = 4;
  /** RegularExpression Id. */
  int create = 5;
  /** RegularExpression Id. */
  int element = 6;
  /** RegularExpression Id. */
  int img = 7;
  /** RegularExpression Id. */
  int header = 8;
  /** RegularExpression Id. */
  int para = 9;
  /** RegularExpression Id. */
  int url = 10;
  /** RegularExpression Id. */
  int decorated_url = 11;
  /** RegularExpression Id. */
  int decorated_text = 12;
  /** RegularExpression Id. */
  int text = 13;
  /** RegularExpression Id. */
  int color = 14;
  /** RegularExpression Id. */
  int font = 15;
  /** RegularExpression Id. */
  int quote = 16;
  /** RegularExpression Id. */
  int alphanumeric = 17;
  /** RegularExpression Id. */
  int sentence = 18;
  /** RegularExpression Id. */
  int string = 19;
  /** RegularExpression Id. */
  int EQUAL = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<OPP>",
    "<OPS>",
    "<NUMBER>",
    "<REALNUMBER>",
    "<create>",
    "<element>",
    "<img>",
    "<header>",
    "<para>",
    "<url>",
    "<decorated_url>",
    "<decorated_text>",
    "<text>",
    "<color>",
    "<font>",
    "\"\\\"\"",
    "<alphanumeric>",
    "<sentence>",
    "<string>",
    "\"=\"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\" \"",
  };

}
