PARSER_BEGIN(Example)

/** Simple brace matcher. */
public class Example {

  /** Main entry point. */
  public static void main(String args[]) throws ParseException {
    Example parser = new Example(System.in);
    parser.Input();
  }

}

PARSER_END(Example)

/** Root production. */
TOKEN :
{
   <create :  ("ADD ") <element>>
}
TOKEN :
{
   <element : <img> | <header> | <para> | <url>>
}

TOKEN :
{
  <img:  ("IMAGE WITH SOURCE ") <quote> <sentence> <quote>>
}
TOKEN :
{
   <header :  ("HEADING ") (<decorated_text>)+>
}
TOKEN :
{
   <para :  ("PARAGRAPH ") (<decorated_text>)+>
}
TOKEN :
{
   <url :  ("LINK ") <decorated_url> (<decorated_text>)+>
}

TOKEN :
{
   <decorated_url: ("http://"|"https://") <string> ("." <string>)+>
}
TOKEN :
{
   <decorated_text :<font> | <color> | <text>>
}


TOKEN :
{
   <text:  ("WITH TEXT ") <quote> <sentence> <quote>>
}
TOKEN :
{
   <color :  ("WITH COLOR ") <quote> <sentence> <quote>>
}
TOKEN :
{
   <font:  ("WITH FONT ") <quote> <sentence> <quote>>
}

TOKEN :
{
    <quote: "\"">
}
TOKEN :
{
    <alphanumeric: ["a"-"z"] | ["A"-"Z"] | ["0"-"9"] | "." | "/" | ":">
}
TOKEN :
{
    <sentence: (<alphanumeric>)+ | ("")>
}

TOKEN :
{
    <string: (["a"-"z"])+ | (["A"-"Z"])+ | (["0"-"9"])+>
}


void Input() throws NumberFormatException:
{
    double res;
}
{

}